export const skillsets: SkillCategory[] = [
  {
    title: "Languages",
    items: [
      "JavaScript (ES6+)",
      "TypeScript",
      "Python",
      "HTML5",
      "CSS3",
      "SQL",
    ],
  },
  {
    title: "Frameworks & Libraries",
    items: [
      "React",
      "Next.js",
      "Vue 3",
      "Vite",
      "Node.js",
      "NestJS",
      "Express",
      "FastAPI",
      "Tailwind CSS",
      "Shadcn UI",
      "React Query",
      "Zustand",
    ],
  },
  {
    title: "APIs & GraphQL",
    items: ["Apollo GraphQL", "Strawberry GraphQL", "REST APIs"],
  },
  {
    title: "Databases & ORM",
    items: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Mongoose",
      "SQLAlchemy",
      "Prisma",
    ],
  },
  {
    title: "Testing",
    items: ["Jest", "React Testing Library", "Playwright"],
  },
  {
    title: "Cloud & Auth",
    items: ["AWS S3", "Azure AD", "JWT Authentication"],
  },
  {
    title: "Version Control",
    items: ["Git", "GitHub", "Bitbucket"],
  },
  {
    title: "Tools & Platforms",
    items: [
      "Storybook",
      "Temporal",
      "Turborepo",
      "Jira",
      "Postman",
      "Figma",
      "Azure DevOps",
      "VSCode",
    ],
  },
  {
    title: "Practices",
    items: [
      "Full-Stack Development",
      "Responsive UI",
      "Design Systems",
      "State Management",
      "Unit & E2E Testing",
      "CI/CD",
      "Agile/Scrum",
      "Accessibility (WCAG/ARIA)",
      "Code Reviews",
      "Performance Optimization",
    ],
  },
];
